services:
    db:
        image: postgres:16
        container_name: studybud-db
        environment:
            POSTGRES_USER: studybud
            POSTGRES_PASSWORD: studybud
            POSTGRES_DB: studybud
        ports:
        - "5432:5432"
        volumes:
        - studybud-db-data:/var/lib/postgresql/data

volumes:
    studybud-db-data: 